import { getPhotos, getTopics } from '@/lib/api'
import { Metadata } from 'next'
import ImageGallery from '@/components/ImageGallery';

export async function generateStaticParams() {
  const topics = await getTopics();

  return topics.map((topic) => ({
    slug: topic.slug,
  }))
}

export const metadata: Metadata = {
  title: `ISplash - Topic`,
  description: 'Generated by create next app',
}

type Props = {
  params: {
    slug: string
  }
}

export default async function Test({ params }: Props) {
  const data = await getPhotos(30, params.slug);

  return (
    <main className='w-full'>
      <ImageGallery images={data} />
    </main>
  )
}