import ImageGallery from "@/components/ImageGallery";
import { getPhotos, getTopics } from "@/lib/api"
import { Metadata } from "next";

export async function generateStaticParams() {
  const topics = await getTopics();

  return topics.map((topic) => ({
    slug: topic.slug,
  }))
}

export const metadata: Metadata = {
  title: `ISplash - Topic`,
  description: 'Generated by create next app',
}

export default async function Test({ params }: { params: { slug: string } }) {
  const data = await getPhotos(30, params.slug);
  
  return (
    <main className="w-full">
      <ImageGallery images={data} />
    </main>
  )
}